name: Deploy to neocities
#Builds the site with 11ty and deploys to Neocities

# only run on changes to main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2

      - name: Install packages
        run: npm ci

      - name: Run npm build
        run: npm run build

    # When the dist_dir is ready, deploy it to neocities
      - name: Deploy to neocities
        uses: bcomnes/deploy-to-neocities@v1.1.13
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          dist_dir: public